service: tokenizacion

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    NODE_ENV: dev

useDotenv: true

custom:
  esbuild:
    bundle: true
    minify: true
  serverless-offline:
    noPrependStageInUrl: true

plugins:
  - serverless-offline
  - serverless-esbuild
  - serverless-dotenv-plugin

package:
  exclude:
    - config/.env.stg
    - config/.env.pro
  include:
    - config/.env.dev

functions:
  jrGenerateToken:
    handler: app/handler.generateToken
    events:
      - http:
          path: /generateToken
          method: post
  jrGetCustomerAccount:
    handler: app/handler.getCustomer
    events:
      - http:
          path: /getCustomer
          method: get


